baseURL = "https://df.alexjj.com/"
languageCode = "en-us"
title = "DF Stories"
theme = "newsprint"
author = "Urist Alex Johnstone"
paginate = 5
canonifyurls = true

[params]

subtitle = "â›ï¸  Dig Deeply; Dig Greedily ğŸ’"
